name: CoolMod
version: 0.5.0
author: StarProgamGamer
main: CoolMod\CoolMod
commands:
 checkop:
  description: Checks if the target player is OP
  permission: CM.command.checkop
  usage: /checkop <player>
 bcast:
  description: Broadcasts a message
  permission: BCast.command
  usage: /bcast <message>
 bpopup:
  description: Broadcasts a popup
  permission: BPopup.command
  usage: /bpopup <message> (it only works when there is at least one player online)
permissions:
 CM.command.checkop:
  description: Checks if the target player is OP
  default: op
 BCast.command:
  description: Broadcasts a popup
  default: op
 BPopup.command:
  description: Broadcasts a popup
  default: op
api: 2.0.0
  